server:
  port: 9000
#logging:
#  level:
#    org.springframework: debug
spring:
  messages:
    basename: messages
  security:
    user:
      name: ats
      password: dkssudgktpdy
management:
  endpoints:
    web:
      exposure:
        include: "*"
